// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-micro.dev/v4"
	"paper-translation/app/file/service/file"
	"paper-translation/pkg/ds"
	"paper-translation/pkg/service"
)

// Injectors from wire.go:

func InitApp() micro.Service {
	registry := service.NewRegistry()
	config := service.NewConfig()
	client := ds.NewMongoClient(config)
	database := ds.NewMongoDatabase(config, client)
	fileRepository := file.NewMongoFileRepository(database)
	redisClient := ds.NewRedisClient(config)
	fileService := file.NewFileService(fileRepository, redisClient)
	microService := NewService(registry, config, fileService)
	return microService
}
