// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-micro.dev/v4"
	"paper-translation/app/paper/service/paper"
	"paper-translation/pkg/ds"
	"paper-translation/pkg/service"
)

// Injectors from wire.go:

func InitApp() micro.Service {
	registry := service.NewRegistry()
	config := service.NewConfig()
	client := ds.NewMongoClient(config)
	database := ds.NewMongoDatabase(config, client)
	mongoPaperRepository := paper.NewMongoPaperRepository(database)
	fileService := NewFileService(registry)
	ocrService := NewOCRService(registry)
	translationService := NewTranslationService(registry)
	emailService := NewEmailService(registry)
	paperService := paper.NewPaperService(mongoPaperRepository, fileService, ocrService, translationService, emailService)
	microService := NewService(registry, config, paperService)
	return microService
}
