// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-micro.dev/v4"
	"paper-translation/app/ocr/service/ocr"
	"paper-translation/pkg/ds"
	ocr2 "paper-translation/pkg/ocr"
	"paper-translation/pkg/oss"
	"paper-translation/pkg/service"
)

// Injectors from wire.go:

func InitApp() micro.Service {
	registry := service.NewRegistry()
	config := service.NewConfig()
	client := ds.NewMongoClient(config)
	database := ds.NewMongoDatabase(config, client)
	mongoOCRRepository := ocr.NewMongoOCRRepository(database)
	clientClient := ocr2.NewAliYunOCR(config)
	ossClient := oss.NewAliYunOSS(config)
	redisClient := ds.NewRedisClient(config)
	ocrService := ocr.NewOCRService(mongoOCRRepository, clientClient, ossClient, redisClient)
	microService := NewService(registry, config, ocrService)
	return microService
}
