// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-micro.dev/v4"
	"paper-translation/app/translation/service/translation"
	"paper-translation/pkg/ds"
	"paper-translation/pkg/service"
	"paper-translation/pkg/signal"
	"paper-translation/pkg/xf-spark"
)

// Injectors from wire.go:

func InitApp() micro.Service {
	registry := service.NewRegistry()
	config := service.NewConfig()
	xfSparkClient := xf_spark.NewXFSpark(config)
	signalFactory := signal.NewSignalFactory(config)
	client := ds.NewRedisClient(config)
	translationService := translation.NewTranslationService(xfSparkClient, signalFactory, client)
	microService := NewService(registry, config, translationService)
	return microService
}
